"""PDF Report Generation for evaluation results."""
from io import BytesIO
from datetime import datetime
from typing import List, Dict, Any, Optional
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, Image, HRFlowable
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT


class PDFReportGenerator:
    """Generate PDF reports for evaluation results."""
    
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()
    
    def _setup_custom_styles(self):
        """Set up custom paragraph styles."""
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Title'],
            fontSize=24,
            spaceAfter=30,
            textColor=colors.HexColor('#6366f1')
        ))
        
        self.styles.add(ParagraphStyle(
            name='SectionHeader',
            parent=self.styles['Heading2'],
            fontSize=14,
            spaceBefore=20,
            spaceAfter=10,
            textColor=colors.HexColor('#1a1a24')
        ))
        
        self.styles.add(ParagraphStyle(
            name='MetricLabel',
            parent=self.styles['Normal'],
            fontSize=10,
            textColor=colors.HexColor('#64748b')
        ))
        
        self.styles.add(ParagraphStyle(
            name='MetricValue',
            parent=self.styles['Normal'],
            fontSize=16,
            fontName='Helvetica-Bold',
            textColor=colors.HexColor('#1a1a24')
        ))
    
    def generate_evaluation_report(
        self,
        results: List[Dict[str, Any]],
        user_info: Optional[Dict[str, Any]] = None,
        title: str = "Hallucination Evaluation Report"
    ) -> BytesIO:
        """
        Generate a PDF report for evaluation results.
        
        Args:
            results: List of evaluation results
            user_info: Optional user information
            title: Report title
            
        Returns:
            BytesIO buffer containing the PDF
        """
        buffer = BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=72
        )
        
        story = []
        
        # Title
        story.append(Paragraph(title, self.styles['CustomTitle']))
        story.append(Paragraph(
            f"Generated on {datetime.now().strftime('%B %d, %Y at %H:%M')}",
            self.styles['Normal']
        ))
        
        if user_info:
            story.append(Paragraph(
                f"User: {user_info.get('username', 'N/A')}",
                self.styles['Normal']
            ))
        
        story.append(Spacer(1, 20))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#e2e8f0')))
        story.append(Spacer(1, 20))
        
        # Summary Statistics
        story.append(Paragraph("Summary Statistics", self.styles['SectionHeader']))
        
        if results:
            stats = self._calculate_stats(results)
            stats_table = self._create_stats_table(stats)
            story.append(stats_table)
            story.append(Spacer(1, 20))
        
        # Detailed Results
        story.append(Paragraph("Evaluation Details", self.styles['SectionHeader']))
        story.append(Spacer(1, 10))
        
        for i, result in enumerate(results[:50], 1):  # Limit to 50 results
            story.extend(self._create_result_section(result, i))
            if i < len(results) and i < 50:
                story.append(Spacer(1, 15))
                story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#e2e8f0')))
                story.append(Spacer(1, 15))
        
        # Footer
        story.append(Spacer(1, 30))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#e2e8f0')))
        story.append(Spacer(1, 10))
        story.append(Paragraph(
            "Generated by HalluciDetect - LLM Hallucination Detection Platform",
            ParagraphStyle(name='Footer', parent=self.styles['Normal'], 
                          fontSize=8, textColor=colors.HexColor('#94a3b8'),
                          alignment=TA_CENTER)
        ))
        
        doc.build(story)
        buffer.seek(0)
        return buffer
    
    def _calculate_stats(self, results: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Calculate summary statistics from results."""
        if not results:
            return {}
        
        total = len(results)
        hallucinations = sum(1 for r in results if r.get('is_hallucination', False))
        
        scores = [r.get('overall_hallucination_score', 0) for r in results]
        avg_score = sum(scores) / total if total > 0 else 0
        
        models = {}
        for r in results:
            model = r.get('model_name', 'Unknown')
            if model not in models:
                models[model] = {'count': 0, 'hallucinations': 0}
            models[model]['count'] += 1
            if r.get('is_hallucination', False):
                models[model]['hallucinations'] += 1
        
        return {
            'total_evaluations': total,
            'hallucination_count': hallucinations,
            'hallucination_rate': (hallucinations / total * 100) if total > 0 else 0,
            'average_score': avg_score * 100,
            'models_tested': len(models),
            'model_breakdown': models
        }
    
    def _create_stats_table(self, stats: Dict[str, Any]) -> Table:
        """Create a summary statistics table."""
        data = [
            ['Metric', 'Value'],
            ['Total Evaluations', str(stats.get('total_evaluations', 0))],
            ['Hallucinations Detected', str(stats.get('hallucination_count', 0))],
            ['Hallucination Rate', f"{stats.get('hallucination_rate', 0):.1f}%"],
            ['Average Score', f"{stats.get('average_score', 0):.1f}%"],
            ['Models Tested', str(stats.get('models_tested', 0))]
        ]
        
        table = Table(data, colWidths=[3*inch, 2*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#6366f1')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 11),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#f8fafc')),
            ('TEXTCOLOR', (0, 1), (-1, -1), colors.HexColor('#1a1a24')),
            ('FONTSIZE', (0, 1), (-1, -1), 10),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#e2e8f0')),
            ('TOPPADDING', (0, 1), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 1), (-1, -1), 8),
        ]))
        
        return table
    
    def _create_result_section(self, result: Dict[str, Any], index: int) -> List:
        """Create a section for a single evaluation result."""
        elements = []
        
        # Result header
        is_hallucination = result.get('is_hallucination', False)
        status = "HALLUCINATION DETECTED" if is_hallucination else "PASSED"
        status_color = colors.HexColor('#ef4444') if is_hallucination else colors.HexColor('#10b981')
        
        elements.append(Paragraph(
            f"<b>#{index}</b> - {result.get('model_name', 'Unknown Model')} | "
            f"<font color='{status_color}'>{status}</font>",
            self.styles['Normal']
        ))
        elements.append(Spacer(1, 5))
        
        # Prompt (truncated)
        prompt = result.get('prompt', '')[:200]
        if len(result.get('prompt', '')) > 200:
            prompt += '...'
        elements.append(Paragraph(f"<b>Prompt:</b> {prompt}", self.styles['Normal']))
        elements.append(Spacer(1, 5))
        
        # Scores
        scores_data = [
            ['Semantic Similarity', 'Fact Check', 'Rule-Based', 'Overall'],
            [
                f"{result.get('semantic_similarity_score', 0)*100:.1f}%",
                f"{result.get('fact_check_score', 0)*100:.1f}%",
                f"{result.get('rule_based_score', 0)*100:.1f}%",
                f"{result.get('overall_hallucination_score', 0)*100:.1f}%"
            ]
        ]
        
        scores_table = Table(scores_data, colWidths=[1.5*inch]*4)
        scores_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#f1f5f9')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#64748b')),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 8),
            ('FONTSIZE', (0, 1), (-1, 1), 10),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e2e8f0')),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ]))
        
        elements.append(scores_table)
        
        return elements
    
    def generate_single_result_report(self, result: Dict[str, Any]) -> BytesIO:
        """Generate a detailed PDF for a single evaluation result."""
        return self.generate_evaluation_report([result], title="Evaluation Result Report")


# Singleton instance
_pdf_generator = None

def get_pdf_generator() -> PDFReportGenerator:
    """Get or create PDFReportGenerator instance."""
    global _pdf_generator
    if _pdf_generator is None:
        _pdf_generator = PDFReportGenerator()
    return _pdf_generator

